#if !canImport(ObjectiveC)
import XCTest

extension BlogPublishTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BlogPublishTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BlogPublishTests.__allTests__BlogPublishTests),
    ]
}
#endif
