name: GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: "swift:5.10"

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Publish
        run: |
          git clone https://github.com/JohnSundell/Publish.git
          cd Publish
          # make # sames not working so i copy/past the content below form make.install
          swift build -c release
          install .build/release/publish-cli /usr/local/bin/publish

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Site
        run: publish generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Output

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.buildnumber.outputs.build_number }}",
              sha: context.sha
            })
